<a href="https://colab.research.google.com/github/ashel1307/Artificial_Intelligence_Lab_SE_A_55/blob/master/DS_Experiment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [111]:
import numpy as np
matrix = np.array ([[1,2,1],[3,7,1],[2,2,7]])

In [112]:
determinant = np.linalg.det(matrix)

print(f"Determinant: {determinant : .2f} ")


Determinant:  1.00 


In [113]:
matrix_inv = np.linalg.inv(matrix)

print("Inverse Matrix:")
print(matrix_inv)

Inverse Matrix:
[[ 47. -12.  -5.]
 [-19.   5.   2.]
 [ -8.   2.   1.]]


In [114]:
B = np.array([9, -5, -9])

X = np.linalg.solve(matrix, B)

print(f"Solution: x = {X[0] :.0f}, y = {X[1] :.0f}, z = {X[2] :.0f}")

Solution: x = 528, y = -214, z = -91
