<a href="https://colab.research.google.com/github/ashel1307/Artificial_Intelligence_Lab_SE_A_55/blob/master/DS_Experiment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A) Create a 3x3 Square Matrix and compute its Determinant

In [6]:
import numpy as np

# Create a 3x3 square matrix
matrix = np.array([
    [2, 4, 1],
    [3, 5, 7],
    [6, 8, 9]
])

# Display the matrix
print("3x3 Matrix:")
print(matrix)

# Assign elements to variables
a = matrix[0][0]
b = matrix[0][1]
c = matrix[0][2]
d = matrix[1][0]
e = matrix[1][1]
f = matrix[1][2]
g = matrix[2][0]
h = matrix[2][1]
i = matrix[2][2]

# Compute determinant manually
determinant = a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

# Display determinant
print("\nDeterminant of the matrix:", determinant)

3x3 Matrix:
[[2 4 1]
 [3 5 7]
 [6 8 9]]

Determinant of the matrix: 32


# B) Find the Inverse of the Matrix

In [7]:
import numpy as np

# Create a 3x3 square matrix
matrix = np.array([
    [2, 4, 1],
    [3, 5, 7],
    [6, 8, 9]
])

# Display the matrix
print("Original Matrix:")
print(matrix)

# Check if determinant is non-zero
determinant = np.linalg.det(matrix)

if determinant != 0:
    # Find inverse
    inverse_matrix = np.linalg.inv(matrix)

    print("\nDeterminant:", determinant)
    print("\nInverse of the matrix:")
    print(inverse_matrix)
else:
    print("\nMatrix is singular (determinant = 0). Inverse does not exist.")


Original Matrix:
[[2 4 1]
 [3 5 7]
 [6 8 9]]

Determinant: 32.000000000000014

Inverse of the matrix:
[[-0.34375 -0.875    0.71875]
 [ 0.46875  0.375   -0.34375]
 [-0.1875   0.25    -0.0625 ]]


# C) Solve the following system of linear equations with matrices using NumPy :
2x + 3y = 10, 4x + 5y = 20

In [8]:
# Import NumPy Library
import numpy as np

# Coefficient matrix (A)
A = np.array([
    [2, 3],
    [4, 5]
])

# Constant matrix (B)
B = np.array([10, 20])

# Solve the system AX = B
solution = np.linalg.solve(A, B)

# Display the results
print("Coefficient Matrix (A):")
print(A)

print("\nConstant Matrix (B):")
print(B)

print("\nSolution:")
print("x =", solution[0])
print("y =", solution[1])


Coefficient Matrix (A):
[[2 3]
 [4 5]]

Constant Matrix (B):
[10 20]

Solution:
x = 5.0
y = 0.0
